name: NASA Project CI
on: #on refers to the triggers that'll cause this workflow to run
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs: 
  build: 
    env:
      CI: true #will help disable watch mode for npm test 
      MONGO_URL: mongodb://127.0.0.1/nasa
    strategy:
      matrix:
        node-version: [17.x, 18.x]
        mongodb-version: ['4.4, 5.0']
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3 #checkout latest version of code from master
      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v3 #the version is so that if a new update comes out it won't break out workflow
        with: 
          node-version: ${{ matrix.node-version }}
      - name: use MongoDB from Github actions
        uses: supercharge/mongodb-github-action@1.8.0
        with: 
          mongodb-version: ${{ matrix.mongodb-version }}
      - run: npm install
      - run: npm run build --prefix client
      - run: npm test 
  # deploy: 
  #   needs: build
